@extends('layout.app')

@section('content')
<div class="max-w-6xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
    
    <!-- Article Header -->
    <header class="mb-6 sm:mb-8">
        <h1 class="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900 mb-3 sm:mb-4 leading-tight">
            {{ $post->judul }}
        </h1>
        
        <div class="flex flex-wrap items-center text-xs sm:text-sm text-gray-600 mb-4 sm:mb-6 gap-2 sm:gap-4">
            <span>{{ $post->created_at->translatedFormat('d F Y') }}</span>
            <span class="hidden sm:inline">•</span>
            <span>{{ $post->author->nama_lengkap ?? 'Admin' }}</span>
        </div>

        @if($post->thumbnail)
            <div class="mb-6 sm:mb-8 flex justify-center">
                <img src="{{ asset('storage/'.$post->thumbnail) }}" 
                     alt="{{ $post->judul }}" 
                     class="w-full max-w-4xl max-h-[450px] object-cover rounded-xl shadow-md">
            </div>
        @endif
    </header>

    <!-- Article Content -->
    <article class="max-w-none mb-8 sm:mb-12 ck-content overflow-hidden">
        <div class="text-gray-800 leading-relaxed text-base sm:text-lg break-words">
            {!! $post->isi !!}
        </div>
    </article>

    <style>
        /* Responsive styles for article content (Synchronized with Admin WYSIWYG) */
        .ck-content ul {
            list-style-type: disc !important;
            padding-left: 2rem !important;
            margin-bottom: 1rem;
        }
        .ck-content ol {
            list-style-type: decimal !important;
            padding-left: 2rem !important;
            margin-bottom: 1rem;
        }
        .ck-content li {
            margin-bottom: 0.25rem;
        }
        .ck-content p {
            margin-bottom: 1rem;
        }
        .ck-content h2 {
            font-size: 1.5rem;
            font-weight: bold;
            margin-top: 1.5rem;
            margin-bottom: 0.5rem;
        }
        .ck-content h3 {
            font-size: 1.25rem;
            font-weight: bold;
            margin-top: 1.25rem;
            margin-bottom: 0.5rem;
        }
        .ck-content h4 {
            font-size: 1.1rem;
            font-weight: bold;
            margin-top: 1rem;
            margin-bottom: 0.5rem;
        }
        .ck-content blockquote {
            border-left: 4px solid #d1d5db;
            padding-left: 1rem;
            color: #6b7280;
            font-style: italic;
            margin-bottom: 1rem;
        }
        .ck-content a {
            color: #2563eb;
            text-decoration: underline;
        }
        .ck-content img {
            max-width: 100%;
            height: auto;
            border-radius: 0.5rem;
            margin: 1rem 0;
        }
        .ck-content table {
            width: 100%;
            overflow-x: auto;
            display: block;
            border-collapse: collapse;
            margin-bottom: 1rem;
        }
        .ck-content table td, .ck-content table th {
            border: 1px solid #d1d5db;
            padding: 0.5rem;
        }
        .ck-content s, .ck-content del, .ck-content strike {
            text-decoration: line-through !important;
        }
        .ck-content u {
            text-decoration: underline !important;
        }
        .ck-content strong, .ck-content b {
            font-weight: bold !important;
        }
        .ck-content i, .ck-content em {
            font-style: italic !important;
        }
        .ck-content iframe {
            max-width: 100%;
            aspect-ratio: 16/9;
        }
        /* Alignment Classes Generated by CKEditor */
        .text-align-left { text-align: left !important; }
        .text-align-center { text-align: center !important; }
        .text-align-right { text-align: right !important; }
        .text-align-justify { text-align: justify !important; }
        .image-style-side { float: right; margin-left: 1rem; max-width: 50%; }
        .image-style-align-left { float: left; margin-right: 1rem; }
        .image-style-align-center { margin-left: auto; margin-right: auto; display: block; }
        .image-style-align-right { float: right; margin-left: 1rem; }
    </style>

    <!-- Like & Share Actions -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between py-4 sm:py-6 border-t border-gray-200 mb-6 sm:mb-8">
        
        <!-- Like Action -->
        <div class="flex items-center gap-2 mb-4 sm:mb-0">
            @auth
            <button onclick="toggleLike({{ $post->id }})" id="like-btn" class="flex items-center gap-2 p-2 rounded-lg transition-colors {{ $post->isLikedBy(auth()->user()) ? 'text-red-500 bg-red-50 hover:bg-red-100' : 'text-gray-500 hover:bg-gray-50 hover:text-red-500' }}" title="Suka">
                <svg id="like-icon" class="w-6 h-6 sm:w-7 sm:h-7 {{ $post->isLikedBy(auth()->user()) ? 'fill-current' : 'fill-none stroke-current' }}" viewBox="0 0 24 24" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                </svg>
                <span id="like-count" class="font-semibold text-lg">{{ $post->likes()->count() }}</span>
            </button>
            @else
            <a href="{{ route('login') }}" class="flex items-center gap-2 p-2 rounded-lg text-gray-500 hover:bg-gray-50 hover:text-red-500 transition-colors" title="Login untuk menyukai">
                <svg class="w-6 h-6 sm:w-7 sm:h-7 fill-none stroke-current" viewBox="0 0 24 24" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                </svg>
                <span class="font-semibold text-lg">{{ $post->likes()->count() }}</span>
            </a>
            @endauth
        </div>

        <div class="flex flex-wrap items-center justify-center gap-2 sm:gap-3">
            <span class="text-xs sm:text-sm text-gray-600 w-full sm:w-auto text-center sm:text-left mb-2 sm:mb-0">Bagikan:</span>
            <div class="flex items-center gap-2">
                <button onclick="share('whatsapp')" class="p-2 sm:p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors" title="WhatsApp">
                    <svg class="w-4 h-4 sm:w-5 sm:h-5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893A11.821 11.821 0 0020.525 3.687"/>
                    </svg>
                </button>
                <button onclick="share('telegram')" class="p-2 sm:p-2 text-blue-500 hover:bg-blue-50 rounded-lg transition-colors" title="Telegram">
                    <svg class="w-4 h-4 sm:w-5 sm:h-5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
                    </svg>
                </button>
                <button onclick="share('facebook')" class="p-2 sm:p-2 text-blue-700 hover:bg-blue-50 rounded-lg transition-colors" title="Facebook">
                    <svg class="w-4 h-4 sm:w-5 sm:h-5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                    </svg>
                </button>
                <button onclick="copyLink()" class="p-2 sm:p-2 text-gray-500 hover:bg-gray-50 rounded-lg transition-colors" title="Copy">
                    <svg class="w-4 h-4 sm:w-5 sm:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Comments Section -->
    <section class="border-t border-gray-200 pt-6 sm:pt-8">
        <h2 class="text-lg sm:text-xl font-bold mb-4 sm:mb-6">Komentar ({{ $post->comments->count() }})</h2>

        @auth
            @if(auth()->user()->isBannedFromForum())
                <div class="mb-6 sm:mb-8 p-4 bg-red-50 border border-red-200 rounded-xl text-center">
                    <h3 class="text-red-700 font-bold mb-2">🚫 Akun Anda Diblokir</h3>
                    <p class="text-sm text-red-600 mb-3">
                        Anda tidak dapat mengirim komentar karena akun Anda telah dilaporkan lebih dari 3 kali.
                    </p>
                    <a href="https://mail.google.com/mail/?view=cm&fs=1&to=keciltikus29@gmail.com&su=Banding%20Akun%20Web" target="_blank" class="inline-block px-4 py-2 bg-red-600 text-white text-sm font-semibold rounded-lg hover:bg-red-700 transition">
                        Ajukan Banding
                    </a>
                </div>
            @else
                <form method="POST" action="{{ route('blog.comment.store', $post) }}" class="mb-6 sm:mb-8">
                    @csrf
                <textarea name="comment" rows="4" 
                          class="w-full border border-gray-300 rounded-lg p-3 sm:p-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none text-sm sm:text-base"
                          placeholder="Tulis komentar Anda..."></textarea>
                <button type="submit" 
                        class="mt-3 sm:mt-4 px-4 sm:px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm sm:text-base">
                    Kirim Komentar
                </button>
            </form>
            @endif
        @else
            <div class="mb-6 sm:mb-8 p-4 sm:p-6 bg-gradient-to-br from-blue-50 to-indigo-100 rounded-xl border-2 border-dashed border-blue-200">
                <div class="text-center">
                    <div class="w-12 h-12 sm:w-16 sm:h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
                        <svg class="w-6 h-6 sm:w-8 sm:h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
                        </svg>
                    </div>
                    <h3 class="text-base sm:text-lg font-semibold text-gray-800 mb-2">Bergabunglah dalam Diskusi!</h3>
                    <p class="text-gray-600 mb-4 text-sm">Login untuk berbagi pendapat tentang artikel ini</p>
                    <div class="flex flex-col gap-3 justify-center">
                        <a href="{{ route('login') }}" 
                           class="inline-flex items-center justify-center px-5 sm:px-6 py-2.5 sm:py-3 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-all duration-200 shadow-sm hover:shadow-md text-sm sm:text-base">
                            <svg class="w-4 h-4 sm:w-5 sm:h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path>
                            </svg>
                            Masuk Sekarang
                        </a>
                        <a href="{{ route('register') }}" 
                           class="inline-flex items-center justify-center px-5 sm:px-6 py-2.5 sm:py-3 bg-white text-blue-600 border border-blue-300 rounded-lg font-medium hover:bg-blue-50 transition-all duration-200 text-sm sm:text-base">
                            <svg class="w-4 h-4 sm:w-5 sm:h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z"></path>
                            </svg>
                            Daftar Gratis
                        </a>
                    </div>
                   
                </div>
            </div>
        @endauth

        <!-- Comments List -->
        <div class="space-y-4 sm:space-y-6">
            @forelse($post->comments as $comment)
                <div class="flex space-x-3 sm:space-x-4">
                    <div class="w-8 h-8 sm:w-10 sm:h-10 rounded-full overflow-hidden flex-shrink-0 border border-gray-200">
                        <img class="w-full h-full object-cover" loading="lazy"
                             src="{{ $comment->user && $comment->user->profile_photo_path ? asset('storage/' . $comment->user->profile_photo_path) : 'https://ui-avatars.com/api/?name='.urlencode($comment->user?->name ?? 'Anonim').'&color=7F9CF5&background=EBF4FF' }}" 
                             alt="{{ $comment->user?->name ?? 'User' }}">
                    </div>
                    <div class="flex-1 min-w-0">
                        <div class="flex flex-col sm:flex-row sm:items-center justify-between w-full mb-1">
                            <h4 class="font-medium text-gray-900 text-sm sm:text-base flex items-center flex-wrap gap-2">
                                @if(auth()->check() && auth()->id() === $comment->user_id)
                                    {{ $comment->user?->name ?? 'Anonim' }} <span class="text-xs text-blue-500 font-normal">(Anda)</span>
                                @else
                                    {{ \App\Helpers\StringHelper::maskName($comment->user?->name ?? 'Anonim') }}
                                @endif

                                @if($comment->user)
                                    @if($comment->user->role_id === 1)
                                        <span class="bg-red-100 text-red-700 text-[10px] sm:text-xs px-2 py-0.5 rounded-full font-bold border border-red-200">Admin</span>
                                    @elseif($comment->user->role_id === 3)
                                        <span class="bg-indigo-100 text-indigo-700 text-[10px] sm:text-xs px-2 py-0.5 rounded-full font-bold border border-indigo-200">Moderator</span>
                                    @endif
                                @endif
                            </h4>
                            @auth
                                @if(auth()->id() !== $comment->user_id && !in_array($comment->user?->role_id, [1, 3]))
                                <button type="button" onclick="openReportModal({{ $comment->id }})" class="text-xs text-gray-400 hover:text-red-500 transition flex items-center gap-1 mt-1 sm:mt-0" title="Laporkan komentar ini">
                                    <i class="fas fa-flag"></i> Laporkan
                                </button>
                                @endif
                            @endauth
                        </div>
                        <p class="text-gray-700 text-sm sm:text-base break-words">{{ $comment->isi }}</p>
                    </div>
                </div>
            @empty
                <p class="text-gray-500 text-center py-6 sm:py-8 text-sm sm:text-base">Belum ada komentar. Jadilah yang pertama!</p>
            @endforelse
        </div>
    </section>

    <!-- Related Articles -->
    @if($relatedPosts->count() > 0)
        <section class="mt-12 sm:mt-16 pt-6 sm:pt-8 border-t border-gray-200">
            <h2 class="text-lg sm:text-xl font-bold mb-4 sm:mb-6">Blog Terkait</h2>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
                @foreach($relatedPosts->take(4) as $related)
                    <article class="group bg-white rounded-lg border border-gray-100 hover:border-gray-200 overflow-hidden transition-all duration-200 hover:shadow-md">
                        <a href="{{ route('blog.show', $related->slug) }}" class="block">
                            @if($related->thumbnail)
                                <div class="aspect-video overflow-hidden">
                                    <img src="{{ asset('storage/'.$related->thumbnail) }}" loading="lazy"
                                         alt="{{ $related->judul }}" 
                                         class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">
                                </div>
                            @else
                                <div class="aspect-video bg-gradient-to-br from-gray-100 to-gray-200 flex items-center justify-center">
                                    <svg class="w-8 h-8 sm:w-12 sm:h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                                    </svg>
                                </div>
                            @endif
                            <div class="p-3 sm:p-4">
                                <h3 class="font-semibold text-gray-900 group-hover:text-blue-600 line-clamp-2 mb-2 leading-snug text-sm sm:text-base">
                                    {{ $related->judul }}
                                </h3>
                                <div class="flex items-center justify-between text-xs sm:text-sm text-gray-500">
                                    <span>{{ $related->created_at->format('d M Y') }}</span>
                                    <span>{{ ceil(str_word_count(strip_tags($related->isi)) / 200) }} min</span>
                                </div>
                            </div>
                        </a>
                    </article>
                @endforeach
            </div>
            
            @if($relatedPosts->hasPages())
                <div class="mt-8 sm:mt-12">
                    {{ $relatedPosts->withQueryString()->links() }}
                </div>
            @endif
        </section>
    @endif
</div>

<!-- Report Modal -->
<div id="reportModal" class="fixed inset-0 z-[100] hidden">
    <!-- Overlay -->
    <div class="absolute inset-0 bg-black/50 backdrop-blur-sm transition-opacity" onclick="closeReportModal()"></div>
    
    <!-- Modal Content -->
    <div class="flex items-center justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:p-0">
        <div class="relative bg-white rounded-2xl text-left overflow-hidden shadow-2xl transform transition-all sm:my-8 sm:max-w-lg w-full border border-gray-100">
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div class="sm:flex sm:items-start">
                    <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                        <i class="fas fa-exclamation-triangle text-red-600"></i>
                    </div>
                    <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
                        <h3 class="text-lg leading-6 font-bold text-gray-900" id="modal-title">
                            Laporkan Komentar
                        </h3>
                        <div class="mt-2">
                            <p class="text-sm text-gray-500 mb-4">
                                Mengapa Anda melaporkan komentar ini? Laporan Anda akan ditinjau oleh tim kami. Jika terbukti melanggar, komentar akan dihapus dan pengguna dapat diberikan sanksi.
                            </p>
                            
                            <form id="reportForm">
                                <input type="hidden" id="report_comment_id" name="comment_id">
                                <div class="space-y-3">
                                    <label class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50 transition">
                                        <input type="radio" name="reason" value="Spam" class="w-4 h-4 text-red-600 focus:ring-red-500 border-gray-300" required>
                                        <span class="ml-3 block text-sm font-medium text-gray-700">Ini adalah Spam / Promosi Ilegal</span>
                                    </label>
                                    <label class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50 transition">
                                        <input type="radio" name="reason" value="Perilaku Kasar" class="w-4 h-4 text-red-600 focus:ring-red-500 border-gray-300">
                                        <span class="ml-3 block text-sm font-medium text-gray-700">Perilaku Kasar / Pelecehan</span>
                                    </label>
                                    <label class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50 transition">
                                        <input type="radio" name="reason" value="Penipuan" class="w-4 h-4 text-red-600 focus:ring-red-500 border-gray-300">
                                        <span class="ml-3 block text-sm font-medium text-gray-700">Penipuan / Menyesatkan</span>
                                    </label>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                <button type="button" onclick="submitReport()" class="w-full inline-flex justify-center rounded-lg border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm transition">
                    Kirim Laporan
                </button>
                <button type="button" onclick="closeReportModal()" class="mt-3 w-full inline-flex justify-center rounded-lg border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm transition">
                    Batal
                </button>
            </div>
        </div>
    </div>
</div>

<script>
function toggleLike(postId) {
    const btn = document.getElementById('like-btn');
    const icon = document.getElementById('like-icon');
    const countSpan = document.getElementById('like-count');
    
    fetch(`/blog/${postId}/like`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        }
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.json();
    })
    .then(data => {
        if (data.status === 'liked') {
            btn.classList.remove('text-gray-500', 'hover:bg-gray-50', 'hover:text-red-500');
            btn.classList.add('text-red-500', 'bg-red-50', 'hover:bg-red-100');
            icon.classList.remove('fill-none', 'stroke-current');
            icon.classList.add('fill-current');
        } else if (data.status === 'unliked') {
            btn.classList.remove('text-red-500', 'bg-red-50', 'hover:bg-red-100');
            btn.classList.add('text-gray-500', 'hover:bg-gray-50', 'hover:text-red-500');
            icon.classList.remove('fill-current');
            icon.classList.add('fill-none', 'stroke-current');
        } else if (data.status === 'error') {
            alert(data.message || 'Terjadi kesalahan.');
        }
        
        if (data.likes_count !== undefined) {
            countSpan.textContent = data.likes_count;
        }
    })
    .catch(error => {
        console.error('Error:', error);
    });
}

function share(platform) {
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(document.title);
    
    if (navigator.share && platform === 'native') {
        navigator.share({
            title: document.title,
            text: document.title,
            url: window.location.href
        }).catch(console.error);
        return;
    }

    const urls = {
        whatsapp: `https://api.whatsapp.com/send?text=${title}%20${url}`,
        telegram: `https://t.me/share/url?url=${url}&text=${title}`,
        facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}`
    };
    
    if (urls[platform]) {
        const width = 600;
        const height = 600;
        const left = (window.innerWidth - width) / 2;
        const top = (window.innerHeight - height) / 2;
        
        // This popup approach ensures the browser uses existing cookies
        // (so they are already logged in to FB/Web WA) or triggers App Deep Linking perfectly.
        window.open(urls[platform], `share_${platform}`, `width=${width},height=${height},top=${top},left=${left},toolbar=0,status=0,menubar=0`);
    }
}

function copyLink() {
    navigator.clipboard.writeText(window.location.href).then(() => {
        const btn = event.target.closest('button');
        const originalHTML = btn.innerHTML;
        btn.innerHTML = '<svg class="w-4 h-4 sm:w-5 sm:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>';
        btn.classList.add('text-green-600', 'bg-green-50');
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
            btn.classList.remove('text-green-600', 'bg-green-50');
            btn.classList.add('text-gray-500');
        }, 2000);
    }).catch(() => {
        const textArea = document.createElement('textarea');
        textArea.value = window.location.href;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        alert('Link berhasil disalin!');
    });
}

// Report Modal Logic
function openReportModal(commentId) {
    document.getElementById('report_comment_id').value = commentId;
    document.getElementById('reportModal').classList.remove('hidden');
    // Reset radio buttons
    const radios = document.querySelectorAll('input[name="reason"]');
    for (let i = 0; i < radios.length; i++) {
        radios[i].checked = false;
    }
}

function closeReportModal() {
    document.getElementById('reportModal').classList.add('hidden');
}

function submitReport() {
    const commentId = document.getElementById('report_comment_id').value;
    const form = document.getElementById('reportForm');
    const reasonInput = form.querySelector('input[name="reason"]:checked');
    
    if (!reasonInput) {
        alert('Silakan pilih alasan pelaporan terlebih dahulu.');
        return;
    }
    
    const reason = reasonInput.value;
    
    fetch(`/blog/comments/${commentId}/report`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        body: JSON.stringify({ reason: reason })
    })
    .then(response => response.json())
    .then(data => {
        closeReportModal();
        if (data.status === 'success') {
            alert('Laporan berhasil dikirim. Terima kasih partisipasinya.');
        } else {
            alert(data.message || 'Terjadi kesalahan saat melaporkan.');
        }
    })
    .catch(error => {
        console.error('Error:', error);
        closeReportModal();
        alert('Terjadi kesalahan jaringan.');
    });
}
</script>
@endsection